# Instructions #
# Step 1: go to https://www.cboe.com/delayed_quotes/spx
# Step 2: type the ticker you want to analyze and the click on Search
# Step 3: click on Option
# Step 4: set all the filters with the option ALL
# Step 5: click on View Chain
# Step 6: scroll down until you see the Download CSV file
# Step 7: save this file in the cboe_file folder inside the R Project
# Step 8: repeat this process as many times as you want (but Ideally you should be analyzing the "same" underlying)
# Step 9: Modify the Local Dataframes and Local Variables to match the info you just downloaded from CBOE
# Step 10: click run - Enjoy!!!!
# Step 11: all the charts generated by this scrip will be saved in the Plots - GEX CBOE Folder
# Tip: Download the files and run this script 1 hour after the market is open (you will get better results)
# Tip: Never download and run this script after the market is close (the numbers wont make any sense)

# Global Variables
options(scipen = 999)
options(dplyr.summarise.inform = FALSE)

# Getting the functions
source(file = "00_scripts/Libraries.R")

# Deleting all the files from Plots - GEX
do.call(file.remove, list(list.files("Plots - GEX CBOE/", full.names = TRUE)))

# Loading the functions
libraries()

# Starting the Timer
tictoc::tic()

# Local Dataframes
db_Tickers <- data.frame(Ticker         = c("SPX", "XSP", "SPY"), # These tickers must match the ones you downloaded from the CBOE webpage
                         Multiplier     = 100,          # Option Multiplier
                         div_yield      = 1.3,          # Dividend Yield of the underlying
                         risk_free_rate = 1.9,          # The Risk Free Rate that you want to use
                         Price_Ratio    = c(1, 10, 10)) # By how much you need to multiply the price to put it at the same level as the Reference Ticker

db_Option_Chain_Combined <- NULL
db_prices_from_CBOE      <- NULL

# Local Variables
Days_In_A_Year      <- 365     # Annual convention to be used in Option Pricing
Label               <- "Sp500" # Label to be use in the Chart Titles
Reference_Ticker    <- "SPX"   # Reference Ticker
MMS_First_Criteria  <- 0.95    # Moneyness criteria for the Implied Volatility Structure
MMS_Second_Criteria <- 1.05    # Moneyness criteria for the Implied Volatility Structure

# Generating the Option Chain
acum_GEX <- NULL
for(CBOE_File in list.files("cboe_file/")){ # CBOE_File <- "qqq_quotedata.csv"
  
  # Extracting the Ticker from the CBOE file
  Ticker_Symbol <- CBOE_File %>% strsplit(split = "_") %>% 
    pluck(1) %>% 
    first() %>% 
    toupper()
  
  # When the file was downloaded (first time) - this will be our date of analysis and will allow us to analyzed old file as well as recently downloaded
  file_downloaded_date <- file.info(str_glue("cboe_file/{CBOE_File}"))$mtime %>% as.Date()
  
  # Looking the characteristics of the Ticker in our Global Dataframe (Ticker Info)
  Ticker_Info_Filtered <- db_Tickers %>% 
    dplyr::filter(Ticker == Ticker_Symbol)
  
  # Reading the data from the CBOE File (General Information)
  CBOE_General_Info <- read.csv(str_glue("cboe_file/{CBOE_File}"), sep = '\t', header = FALSE) %>%
    dplyr::slice(1:2) %>% 
    splitstackshape::cSplit("V1",",")
  
  Spot_Price <- CBOE_General_Info$V1_2[1] %>% 
    str_remove_all("Last: ") %>% 
    as.numeric()
  
  # Saving the info of the spot price from the CBOE File
  db_prices_from_CBOE <- db_prices_from_CBOE %>%
    rbind(data.frame(Reference_Price = Spot_Price,
                     Ticker          = Ticker_Symbol))
  
  # Extracting the Option Chain
  db_Option_Chain <- read.csv(str_glue("cboe_file/{CBOE_File}"), sep = '\t', header = FALSE) %>%
    dplyr::slice(3:n()) %>% 
    splitstackshape::cSplit("V1",",") %>%
    janitor::row_to_names(1)
  
  # Extracting data from the Calls and calculating GEX
  # GEX - Calls
  db_Option_Chain_Calls <- db_Option_Chain %>%
    dplyr::select(1, 8, 11, 12) %>%
    dplyr::mutate(Expiration_Month  = case_when(substr(`Expiration Date`, 5, 7) == "Jan" ~ "01",
                                                substr(`Expiration Date`, 5, 7) == "Feb" ~ "02",
                                                substr(`Expiration Date`, 5, 7) == "Mar" ~ "03",
                                                substr(`Expiration Date`, 5, 7) == "Apr" ~ "04",
                                                substr(`Expiration Date`, 5, 7) == "May" ~ "05",
                                                substr(`Expiration Date`, 5, 7) == "Jun" ~ "06",
                                                substr(`Expiration Date`, 5, 7) == "Jul" ~ "07",
                                                substr(`Expiration Date`, 5, 7) == "Aug" ~ "08",
                                                substr(`Expiration Date`, 5, 7) == "Sep" ~ "09",
                                                substr(`Expiration Date`, 5, 7) == "Oct" ~ "10",
                                                substr(`Expiration Date`, 5, 7) == "Nov" ~ "11",
                                                substr(`Expiration Date`, 5, 7) == "Dec" ~ "12",
                                                TRUE ~ substr(`Expiration Date`, 5, 7)),
                  Expiration_Day        = substr(`Expiration Date`, 9, 10),
                  Expiration_Year       = substr(`Expiration Date`, 11, 15),
                  Fixed_Expiration_Date = str_glue("{Expiration_Day}/{Expiration_Month}/{Expiration_Year}") %>% as.Date(format = "%d/%m/%Y"),
                  Spot_Price            = Spot_Price) %>%
    janitor::clean_names() %>%
    dplyr::select(fixed_expiration_date, iv, open_interest, strike, spot_price) %>%
    dplyr::mutate(time_expiration_years = (((fixed_expiration_date %>% as.Date()) - file_downloaded_date) %>% as.numeric())/Days_In_A_Year,
                  time_expiration_years = case_when(time_expiration_years == 0 ~ 1/Days_In_A_Year, TRUE ~ time_expiration_years), # For 0 DTE options, setting DTE = 1 day, otherwise they get excluded
                  Ticker                = Ticker_Symbol,
                  type                  = "Calls") %>%
    left_join(db_Tickers, by = "Ticker") %>% 
    dplyr::mutate(Scenarios  = case_when(lubridate::week(fixed_expiration_date) == lubridate::week(file_downloaded_date) ~ "W/out this week",
                                         lubridate::month(fixed_expiration_date) == lubridate::month(file_downloaded_date) ~ "W/out this month",
                                         TRUE ~ "The Rest"))
  
  # GEX Calculations
  GEX_Calls <- greeks(bscall(s  = db_Option_Chain_Calls$spot_price,
                             k  = db_Option_Chain_Calls$strike %>% as.numeric(),
                             v  = db_Option_Chain_Calls$iv %>% as.numeric(),
                             r  = db_Option_Chain_Calls$risk_free_rate/100,
                             tt = db_Option_Chain_Calls$time_expiration_years,
                             d  = db_Option_Chain_Calls$div_yield/100), complete = TRUE) %>%
    dplyr::select(k, s, Gamma) %>%
    dplyr::mutate(Date       = db_Option_Chain_Calls$fixed_expiration_date,
                  OI         = db_Option_Chain_Calls$open_interest %>% as.numeric(),
                  type       = "Calls",
                  Mul        = db_Option_Chain_Calls$Multiplier,
                  PriceRatio = db_Option_Chain_Calls$Price_Ratio,
                  GEX        = +1 * Gamma * Mul * OI * s^2 * 0.01) %>%
    dplyr::select(Date, k, s, GEX, PriceRatio, type)
  
  # GEX - Puts
  db_Option_Chain_Puts <- db_Option_Chain %>%
    dplyr::select(1, 19, 22, 12) %>%
    dplyr::mutate(Expiration_Month  = case_when(substr(`Expiration Date`, 5, 7) == "Jan" ~ "01",
                                                substr(`Expiration Date`, 5, 7) == "Feb" ~ "02",
                                                substr(`Expiration Date`, 5, 7) == "Mar" ~ "03",
                                                substr(`Expiration Date`, 5, 7) == "Apr" ~ "04",
                                                substr(`Expiration Date`, 5, 7) == "May" ~ "05",
                                                substr(`Expiration Date`, 5, 7) == "Jun" ~ "06",
                                                substr(`Expiration Date`, 5, 7) == "Jul" ~ "07",
                                                substr(`Expiration Date`, 5, 7) == "Aug" ~ "08",
                                                substr(`Expiration Date`, 5, 7) == "Sep" ~ "09",
                                                substr(`Expiration Date`, 5, 7) == "Oct" ~ "10",
                                                substr(`Expiration Date`, 5, 7) == "Nov" ~ "11",
                                                substr(`Expiration Date`, 5, 7) == "Dec" ~ "12",
                                                TRUE ~ substr(`Expiration Date`, 5, 7)),
                  Expiration_Day        = substr(`Expiration Date`, 9, 10),
                  Expiration_Year       = substr(`Expiration Date`, 11, 15),
                  Fixed_Expiration_Date = str_glue("{Expiration_Day}/{Expiration_Month}/{Expiration_Year}") %>% as.Date(format = "%d/%m/%Y"),
                  Spot_Price            = Spot_Price) %>%
    janitor::clean_names() %>%
    dplyr::select(fixed_expiration_date, iv, open_interest, strike, spot_price) %>%
    dplyr::mutate(time_expiration_years = (((fixed_expiration_date %>% as.Date()) - file_downloaded_date) %>% as.numeric())/Days_In_A_Year,
                  time_expiration_years = case_when(time_expiration_years == 0 ~ 1/Days_In_A_Year, TRUE ~ time_expiration_years), # For 0 DTE options, setting DTE = 1 day, otherwise they get excluded
                  Ticker                = Ticker_Symbol,
                  type                  = "Puts") %>%
    left_join(db_Tickers, by = "Ticker") %>% 
    dplyr::mutate(Scenarios  = case_when(lubridate::week(fixed_expiration_date) == lubridate::week(file_downloaded_date) ~ "W/out this week",
                                         lubridate::month(fixed_expiration_date) == lubridate::month(file_downloaded_date) ~ "W/out this month",
                                         TRUE ~ "The Rest"))
  
  # GEX Calculations
  GEX_Puts <- greeks(bsput(s  = db_Option_Chain_Puts$spot_price,
                           k  = db_Option_Chain_Puts$strike %>% as.numeric(),
                           v  = db_Option_Chain_Puts$iv %>% as.numeric(),
                           r  = db_Option_Chain_Puts$risk_free_rate/100,
                           tt = db_Option_Chain_Puts$time_expiration_years,
                           d  = db_Option_Chain_Puts$div_yield/100), complete = TRUE) %>%
    dplyr::select(k, s, Gamma) %>%
    dplyr::mutate(Date       = db_Option_Chain_Puts$fixed_expiration_date,
                  OI         = db_Option_Chain_Puts$open_interest %>% as.numeric(),
                  type       = "Puts",
                  Mul        = db_Option_Chain_Puts$Multiplier,
                  PriceRatio = db_Option_Chain_Puts$Price_Ratio,
                  GEX        = -1 * Gamma * Mul * OI * s^2 * 0.01) %>%
    dplyr::select(Date, k, s, GEX, PriceRatio, type)
  
  # Combining all the DB of Options
  db_Option_Chain_Combined <- db_Option_Chain_Combined %>%
    rbind(db_Option_Chain_Calls) %>%
    rbind(db_Option_Chain_Puts)
  
  # Combining all the GEX DB
  acum_GEX <- acum_GEX %>%
    rbind(GEX_Calls) %>%
    rbind(GEX_Puts)
}

# Adjusting Strikes and Spot to the reference ticker
acum_GEX <- acum_GEX %>%
  dplyr::mutate(k = k * PriceRatio,
                s = s * PriceRatio)

# Selecting the Reference Price
Reference_Price <- db_prices_from_CBOE %>% 
  dplyr::filter(Ticker == Reference_Ticker) %>%
  dplyr::select(Reference_Price) %>% pull(1)

# Netting GEX across all the strikes (Charts)
p <- acum_GEX %>%
  dplyr::select(k, GEX) %>%
  dplyr::group_by(k) %>%
  dplyr::filter(k > Reference_Price*0.80 & k < Reference_Price*1.20) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  purrr::set_names(c("Strike", "Gamma Exposure")) %>%
  ggplot(aes(x = Strike, y = `Gamma Exposure`)) +
  geom_bar(stat = "identity") +
  geom_vline(xintercept = Reference_Price, linetype = "dotted", color = "blue", size = 0.9) +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title    = str_glue("Total Gamma Exposure: {dollar_format()(sum(acum_GEX$GEX)/1000000000)} Billions per 1% move in the SP500"),
       subtitle = str_glue("Assuming dealers are long calls and short puts."),
       caption  = "Data Source: CBOE.",
       x = "Strike Price",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal()

p

ggsave("GEX_vs_Strikes.png", plot = p, device = "png", path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in") 

# GEX (Next Two Months)
p <- acum_GEX %>%
  dplyr::select(Date, GEX) %>%
  dplyr::group_by(Date) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  dplyr::mutate(Month = lubridate::month(Date),
                Month_Filter = ifelse(Date <= Sys.Date() + 60, "Yes", "No")) %>%
  dplyr::filter(Month_Filter == "Yes") %>%
  dplyr::select(Date, GEX_NET) %>%
  purrr::set_names(c("Date", "Gamma Exposure")) %>%
  ggplot(aes(x = Date, y = `Gamma Exposure`)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title    = str_glue("Total Gamma Exposure by Expiration Date - Next Two Months"),
       subtitle = str_glue("Assuming dealers are long calls and short puts."),
       caption  = "Data Source: CBOE.",
       x = "Expiration Date",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal()

p

ggsave("GEX_vs_Next_Two_Months.png", plot = p, device = "png", path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in") 

# GEX across Strikes and option type
Colour <- c(Calls = "green", Puts = "red")

p <- acum_GEX %>%
  dplyr::select(k, type, GEX) %>%
  dplyr::filter(k > Reference_Price*0.80 & k < Reference_Price*1.20) %>%
  dplyr::group_by(k, type) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  purrr::set_names(c("Strike", "Type", "Gamma Exposure")) %>%
  ggplot(aes(x = Strike, y = `Gamma Exposure`, fill = Type)) +
  geom_vline(xintercept = Reference_Price, linetype = "dotted", color = "blue", size = 0.9) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values=Colour) +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title    = str_glue("Total Gamma Exposure: {dollar_format()(sum(acum_GEX$GEX)/1000000000)} Billions per 1% move in the SP500"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering Options on the {Label})."),
       caption  = "Data Source: CBOE.",
       x = "Strike Price",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal() +
  theme(legend.title = element_blank())

p

ggsave("GEX_vs_Option_Types.png", plot = p, device = "png", path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in") 

# Calculating the Gamma Exposure Profile
db_GEX_Profile <- NULL 
GEX_blocks     <- c("All expirations", db_Option_Chain_Combined$Scenarios %>% unique() %>% head(n = 2))

for(blocks in GEX_blocks){ # blocks <- "All expirations"
  
  # Filtering
  if(blocks == "All expirations"){
    db_Option_Chain_New <- db_Option_Chain_Combined
    block_Label <- "All expirations"
  }else if(blocks == "W/out this week"){
    db_Option_Chain_New <- db_Option_Chain_Combined %>% dplyr::filter(!Scenarios %in% c("All expirations", "W/out this week"))
    block_Label <- "W/out this week"
  }else{
    db_Option_Chain_New <- db_Option_Chain_Combined %>% dplyr::filter(!Scenarios %in% c("All expirations", "W/out this week", "W/out this month"))
    block_Label <- "W/out this month"
  }
  
  # Setting the Delta in price
  Spot_Steps <- seq(-20, 20, 0.1)
  
  for(new_step in Spot_Steps){ # new_step <- 0
    
    # GEX for the Calls
    # CALLS
    db_Options_Type_Subset <- db_Option_Chain_New %>% dplyr::filter(type == "Calls")
    
    GEX_Calls <- greeks(bscall(s  = db_Options_Type_Subset$spot_price*(1 + new_step/100),
                               k  = db_Options_Type_Subset$strike %>% as.numeric(),
                               v  = db_Options_Type_Subset$iv %>% as.numeric(),
                               r  = db_Options_Type_Subset$risk_free_rate/100,
                               tt = db_Options_Type_Subset$time_expiration_years,
                               d  = db_Options_Type_Subset$div_yield/100), complete = TRUE) %>%
      dplyr::select(k, s, Gamma) %>%
      dplyr::mutate(Date       = db_Options_Type_Subset$fixed_expiration_date,
                    OI         = db_Options_Type_Subset$open_interest %>% as.numeric(),
                    type       = "Calls",
                    Mul        = db_Options_Type_Subset$Multiplier,
                    PriceRatio = db_Options_Type_Subset$Price_Ratio,
                    GEX        = +1 * Gamma * Mul * OI * s^2 * 0.01)
    
    # PUTS
    db_Options_Type_Subset <- db_Option_Chain_New %>% dplyr::filter(type == "Puts")
    
    GEX_Puts <- greeks(bsput(s  = db_Options_Type_Subset$spot_price*(1 + new_step/100),
                             k  = db_Options_Type_Subset$strike %>% as.numeric(),
                             v  = db_Options_Type_Subset$iv %>% as.numeric(),
                             r  = db_Options_Type_Subset$risk_free_rate/100,
                             tt = db_Options_Type_Subset$time_expiration_years,
                             d  = db_Options_Type_Subset$div_yield/100), complete = TRUE) %>%
      dplyr::select(k, s, Gamma) %>%
      dplyr::mutate(Date       = db_Options_Type_Subset$fixed_expiration_date,
                    OI         = db_Options_Type_Subset$open_interest %>% as.numeric(),
                    type       = "Puts",
                    Mul        = db_Options_Type_Subset$Multiplier,
                    PriceRatio = db_Options_Type_Subset$Price_Ratio,
                    GEX        = -1 * Gamma * Mul * OI * s^2 * 0.01)
    
    # Combining all the GEX DB
    db_GEX_Spot <- GEX_Puts %>% rbind(GEX_Calls)
    
    # Saving the calculations in a provisional Dataframe
    db_GEX_Profile_prov <- data.frame(Spot_Change = new_step,
                                      GEX         = sum(db_GEX_Spot$GEX),
                                      Expiration  = block_Label)
    
    # Accumulating 
    db_GEX_Profile <- db_GEX_Profile %>% rbind(db_GEX_Profile_prov)
  }
}

Gamma_Flip <- db_GEX_Profile %>%
  dplyr::filter(Expiration == "All expirations") %>%
  dplyr::mutate(Flip = ifelse(dplyr::lead(GEX > 0) & GEX < 0, "Yes", "No")) %>%
  dplyr::filter(Flip == "Yes") %>%
  dplyr::select(Spot_Change) %>%
  pull(1) %>% first()

# GEX Profile applying locally weighted scatterplot smoothing (removing the noice of the calculations)
p <- db_GEX_Profile %>%
  dplyr::filter(Expiration == "All expirations") %>%
  dplyr::mutate(Spot_Change = lowess(Spot_Change, GEX, f = 1/10) %>% pluck(1),
                GEX         = (lowess(Spot_Change, GEX, f = 1/10) %>% pluck(2))/1000000000) %>%
  ggplot(aes(Spot_Change/100, GEX)) + 
  geom_rect(inherit.aes = TRUE,
            aes(xmin = -Inf, xmax = -0.015, ymin = -Inf, ymax = +Inf), 
            fill = 'red', alpha = 0.005) +
  geom_rect(inherit.aes = TRUE,
            aes(xmin = +0.015, xmax = +Inf, ymin = -Inf, ymax = +Inf), 
            fill = 'green', alpha = 0.005) +
  geom_rect(inherit.aes = TRUE,
            aes(xmin = -0.015, xmax = +0.015, ymin = -Inf, ymax = +Inf), 
            fill = 'orange', alpha = 0.005) +
  geom_line(size = 1.3, colour = "black") +
  geom_vline(xintercept = c(0, Gamma_Flip/100), linetype = c("twodash", "dotted"), color = c("steelblue", "red"), size = 0.9) +
  geom_hline(yintercept = c(sum(acum_GEX$GEX)/1000000000, 0), linetype = c("twodash", "dotted"), color = c("steelblue", "red"), size = 0.9) +
  labs(title    = str_glue("Gamma Exposure Profile of the SP500. All expirations."),
       subtitle = str_glue("Gamma Flip at {round(Gamma_Flip, digits = 2)}% of current price (meaning at: {round(Reference_Price*(1+Gamma_Flip/100), digits = 2)}). This study is considering Options on the {Label}."),
       caption  = "Data Source: CBOE.",
       x = "Change in SPX Price",
       y = "Spot Gamma Exposure (Billions)") +
  scale_y_continuous(labels = scales::dollar_format(),
                     breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = scales::pretty_breaks(n = 10),
                     sec.axis = sec_axis(trans = ~ . * Reference_Price + Reference_Price, name = "SPX Price", breaks = scales::pretty_breaks(n = 10))) +
  theme(legend.title = element_blank())  

p

ggsave("GEX_Profile_All_Expirations.png", plot = p, device = "png", path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in")


# Analyzing the Impact of Different Expiration.
p <- db_GEX_Profile %>%
  dplyr::group_by(Expiration) %>%
  dplyr::mutate(Spot_Change = lowess(Spot_Change, GEX, f = 1/10) %>% pluck(1),
                GEX         = (lowess(Spot_Change, GEX, f = 1/10) %>% pluck(2))/1000000000) %>%
  ggplot(aes(Spot_Change/100, GEX, group = Expiration, colour = Expiration)) + 
  theme_minimal() +
  scale_color_viridis(discrete = TRUE) +
  geom_vline(xintercept = c(0, Gamma_Flip/100), linetype = c("twodash", "dotted"), color = c("steelblue", "red"), size = 0.9) +
  geom_hline(yintercept = c(sum(acum_GEX$GEX)/1000000000, 0), linetype = c("twodash", "dotted"), color = c("steelblue", "red"), size = 0.9) +
  geom_line(size = 1.3) +
  labs(title    = str_glue("Gamma Exposure Profile of the SP500. Analyzing different Scenarios."),
       subtitle = str_glue("Gamma Flip at {round(Gamma_Flip, digits = 2)}% of current price (meaning at: {round(Reference_Price*(1+Gamma_Flip/100), digits = 2)}). This study is considering Options on the {Label}."),
       caption  = "Data Source: CBOE.",
       x = "Change in SPX Price",
       y = "Spot Gamma Exposure (Billions)") +
  scale_y_continuous(labels = scales::dollar_format(),
                     breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = scales::pretty_breaks(n = 10),
                     sec.axis = sec_axis(trans = ~ . * Reference_Price + Reference_Price, name = "SPX Price", breaks = scales::pretty_breaks(n = 10))) +
  theme(legend.title = element_blank())  


p

ggsave("GEX_Profile_Scenarios.png", plot = p, device = "png", path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in") 

# Getting the VIX
db_Volatility <- tq_get("^VIX",
                        from = Sys.Date() - lubridate::years(2),
                        to   = Sys.Date(),
                        get  = "stock.prices",
                        complete_cases = TRUE) %>%
  dplyr::select(date, adjusted) %>%
  left_join(tq_get("SPY",
                   from = Sys.Date() - lubridate::years(2),
                   to   = Sys.Date(),
                   get  = "stock.prices",
                   complete_cases = TRUE) %>%
              dplyr::select(date, adjusted) %>%
              dplyr::mutate(Ret      = TTR::ROC(adjusted, n = 1, type = "discrete"),
                            Real_Vol = roll::roll_sd(Ret, width = 22)*100*sqrt(252)) %>%
              dplyr::select(date, Real_Vol), by = "date") %>%
  na.omit() %>%
  dplyr::mutate(Spread = adjusted - Real_Vol) %>%
  purrr::set_names(c("Date", "Implied Volatility", "Realized Volatility", "Spread"))

p_volatilites <- db_Volatility %>%
  dplyr::select(Date, `Implied Volatility`, `Realized Volatility`) %>%
  pivot_longer(names_to = "Type", values_to = "Volatility", -Date) %>%
  ggplot(aes(x = Date, y = Volatility/100, colour = Type)) +
  geom_line(size = 0.7) +
  theme_bw() +
  labs(title    = "VIX vs Realized SP500 short-term Volatility",
       subtitle = "Volatility behavior of the SP500",
       caption  = "",
       x        = "",
       y        = "") +
  scale_y_continuous(labels = scales::percent) + 
  theme(legend.title = element_blank()) +
  theme(legend.position="bottom")

p_spread <- db_Volatility %>%
  dplyr::select(Date, Spread) %>%
  dplyr::mutate(Mean_Vol = roll::roll_mean(Spread, width = 50)) %>%
  na.omit() %>%
  purrr::set_names(c("Date", "Spread", "Mean")) %>%
  ggplot() +
  geom_line(aes(x = Date, y = Spread/100), size = 0.7) +
  geom_line(aes(x = Date, y = Mean/100), size = 1.1, colour = "red") +
  theme_bw() +
  labs(title    = "Volatility Spread",
       subtitle = "How expensive/cheap is the current volatility?",
       caption  = "",
       x        = "",
       y        = "") +
  scale_y_continuous(labels = scales::percent) + 
  theme(legend.title = element_blank())

p_vix <- db_Volatility %>%
  dplyr::select(Date, `Implied Volatility`) %>%
  purrr::set_names(c("Date", "IV")) %>%
  bind_rows(data.frame(Date = Sys.Date(),
                       IV   = getQuote("^VIX") %>% dplyr::select(Last) %>% pull(1))) %>%
  ggplot(aes(x = Date, y = IV/100)) +
  geom_line(size = 0.7) +
  geom_smooth(method = 'loess', formula = 'y ~ x') +
  theme_bw() +
  labs(title    = "CBOE Volatility Index",
       subtitle = "Short-term trend of the Implied Volatility",
       caption  = "Data Source: Yahoo Finance.",
       x        = "",
       y        = "") +
  scale_y_continuous(labels = scales::percent) + 
  theme(legend.title = element_blank()) +
  geom_hline(yintercept = 0.25, linetype = "dashed", color = "red", size = 1.2)

grid.arrange(p_volatilites, arrangeGrob(p_spread, p_vix, ncol=2), nrow = 2)

ggsave("VIX_Analysis.png", plot = grid.arrange(p_volatilites, arrangeGrob(p_spread, p_vix, ncol=2), nrow = 2), path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in") 

# Extracting the VIX Structure from the Option Chain
ATM_Price         <- Reference_Price
MoneynessFC_Price <- ATM_Price*MMS_First_Criteria
MoneynessSC_Price <- ATM_Price*MMS_Second_Criteria

p <- db_Option_Chain_Combined %>% 
  dplyr::select(fixed_expiration_date, type, iv, strike, Price_Ratio) %>%
  dplyr::mutate(strike = (strike %>% as.numeric()) * Price_Ratio) %>%
  dplyr::filter(type == "Puts" & fixed_expiration_date >= file_downloaded_date) %>%
  dplyr::mutate(final_date = fixed_expiration_date %>% as.Date()) %>%
  dplyr::mutate(VST = ifelse(dplyr::lead(strike, n = 1) > ATM_Price & dplyr::lag(strike, n = 1) < ATM_Price, "ATM", 
                             ifelse(dplyr::lead(strike, n = 1) > MoneynessFC_Price & dplyr::lag(strike, n = 1) < MoneynessFC_Price, str_glue("MM{MMS_First_Criteria*100}"), 
                                    ifelse(dplyr::lead(strike, n = 1) > MoneynessSC_Price & dplyr::lag(strike, n = 1) < MoneynessSC_Price, str_glue("MM{MMS_Second_Criteria*100}"), "")))) %>% 
  dplyr::filter(VST != "") %>%
  dplyr::select(final_date, iv, VST) %>%
  dplyr::group_by(final_date, VST) %>%
  dplyr::summarise(Mean_IV = mean(iv %>% as.numeric()), .groups = "drop") %>%
  dplyr::mutate(VST = case_when(VST == str_glue("MM{MMS_First_Criteria*100}") ~ str_glue("Moneyness {MMS_First_Criteria*100}%"),
                                VST == str_glue("MM{MMS_Second_Criteria*100}") ~ str_glue("Moneyness {MMS_Second_Criteria*100}%"),
                                TRUE ~ VST)) %>%
  dplyr::group_by(VST) %>%
  dplyr::mutate(Mean_IV = (lowess(final_date, Mean_IV, f = 1/2) %>% pluck(2))) %>%
  ggplot(aes(x = final_date, y = Mean_IV, colour = VST)) +
  geom_line(size = 0.9) +
  labs(title    = "Implied Volatility Structure",
       subtitle = "Smoothed data extracted from the Option Chain",
       caption  = "Data Source: CBOE.",
       x        = "",
       y        = "Implied Volatility") +
  scale_y_continuous(labels = scales::percent) +
  theme(legend.title = element_blank(),
        legend.position = "bottom")

p

ggsave("vix_structure.png", plot = p, path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in") 

# Stoping the Timer
tictoc::toc()
