# Instructions #
# Step 1: click run - Enjoy!!!!
# Step 2: all the charts generated by this scrip will be saved in the Plots - GEX Yahoo Folder
# Tip: Run this script 1 hour after the market is open (you will get better results)
# Tip: Never run this script after the market is close (the numbers wont make any sense)

# Global Variables
options(scipen = 999)
options(dplyr.summarise.inform = FALSE)

# Getting the functions
source(file = "00_scripts/getting_option_chain.R")
source(file = "00_scripts/Libraries.R")

# Loading the functions
libraries()

# Deleting all the files from Plots - GEX
do.call(file.remove, list(list.files("Plots - GEX Yahoo/", full.names = TRUE)))

# Global Variables
options(scipen = 999)
options(dplyr.summarise.inform = FALSE)

# Setting the Region
environment_r <- "EU" # Could be EU or US

# Local Dataframes
db_Ratios <- data.frame(Symbol         = c("^SPX", "^XSP", "SPY"),
                        Price_Ratios   = c(1, 10, 10)) %>%
  dplyr::mutate(Spot_Price = getQuote(Symbol)$Last)

# Local Variables
Multiplier     <- 100
div_yield      <- 1.3
risk_free_rate <- 1.9
SPX_Price      <- getQuote(db_Ratios$Symbol[1])$Last
ticker_label   <- "SPX, XSP and SPY"

# Setting the years for the Option Chain
sYear  <- lubridate::year(Sys.Date())
eYear  <- lubridate::year(Sys.Date()) + 1

# Getting the Option Chain from Yahoo Finance
option_chain_yahoo <- NULL

for(i in db_Ratios$Symbol){ # i <- "SPY"
  db_option <- getOptionChain(i, src = "yahoo", Exp = str_glue("{sYear}/{eYear}")) %>%
    unlist(recursive = FALSE) %>%
    enframe() %>%
    unnest(cols = c(value)) %>%
    dplyr::mutate(Symbol = i)
  
  option_chain_yahoo <- bind_rows(option_chain_yahoo, db_option)
}

# Removing NAs
option_chain_yahoo <- option_chain_yahoo %>% replace(is.na(.), 0)

# Fixing and Enhancing the database
option_chain_yahoo_enhanced <- option_chain_yahoo %>%
  left_join(db_Ratios, by = "Symbol") %>%
  dplyr::mutate(Symbol = case_when(Symbol == "^SPX" ~ "SPX", TRUE ~ Symbol))

# Addaping the structure of the option chain to US or EU machines
if(environment_r == "US"){
  # Fixing some formats
  db_option_chain_final <- option_chain_yahoo_enhanced %>%
    dplyr::mutate(data_month = substr(name, 1, 3),  # Extracting just the portion related to the month
                  data_day   = substr(name, 5, 6),  # Extracting just the portion related to the day
                  data_year  = substr(name, 8, 11), # Extracting just the portion related to the year
                  type       = substr(name, 13, length(name)),
                  data_month = case_when(data_month == "Jan" ~ "01",
                                         data_month == "Feb" ~ "02",
                                         data_month == "Mar" ~ "03",
                                         data_month == "Apr" ~ "04",
                                         data_month == "May" ~ "05",
                                         data_month == "Jun" ~ "06",
                                         data_month == "Jul" ~ "07",
                                         data_month == "Aug" ~ "08",
                                         data_month == "Sep" ~ "09",
                                         data_month == "Oct" ~ "10",
                                         data_month == "Nov" ~ "11",
                                         data_month == "Dec" ~ "12",
                                         TRUE ~ data_month),
                  final_date   = as.Date(str_glue("{data_year}-{data_month}-{data_day}"), format = "%Y-%m-%d"),
                  Time_Process = Sys.time()) %>%
    dplyr::select(final_date, type, Strike, Bid, Ask, OI, IV, Symbol, ITM, Time_Process, Price_Ratios, Spot_Price) %>% 
    replace(is.na(.), 0)
}else{
  # Fixing some formats
  db_option_chain_final <- option_chain_yahoo_enhanced %>%
    dplyr::mutate(data_month = substr(name, 1, 3),  # Extracting just the portion related to the month
                  data_day   = substr(name, 6, 7),  # Extracting just the portion related to the day
                  data_year  = substr(name, 9, 12), # Extracting just the portion related to the year
                  type       = substr(name, 14, length(name)),
                  data_month = case_when(data_month == "ene" ~ "01",
                                         data_month == "feb" ~ "02",
                                         data_month == "mar" ~ "03",
                                         data_month == "abr" ~ "04",
                                         data_month == "may" ~ "05",
                                         data_month == "jun" ~ "06",
                                         data_month == "jul" ~ "07",
                                         data_month == "ago" ~ "08",
                                         data_month == "sep" ~ "09",
                                         data_month == "oct" ~ "10",
                                         data_month == "nov" ~ "11",
                                         data_month == "dic" ~ "12",
                                         TRUE ~ data_month),
                  final_date   = as.Date(str_glue("{data_year}-{data_month}-{data_day}"), format = "%Y-%m-%d"),
                  Time_Process = Sys.time()) %>%
    dplyr::select(final_date, type, Strike, Bid, Ask, OI, IV, Symbol, ITM, Time_Process, Price_Ratios, Spot_Price) %>%
    replace(is.na(.), 0)
}

# Adding the Current Prices and Time to Expiration (in Years)
db_option_chain_final <- db_option_chain_final %>%
  dplyr::mutate(type = case_when(type == "calls" ~ "Calls",
                                 TRUE ~ "Puts"),
                time_expiration_years = (((final_date %>% as.Date()) - Sys.Date()) %>% as.numeric())/365,
                time_expiration_years = case_when(time_expiration_years == 0 ~ 1, TRUE ~ time_expiration_years), # For 0 DTE options, I'm setting DTE = 1 day, otherwise they get excluded
                Expiration_Date = case_when(lubridate::week(final_date) == lubridate::week(Sys.Date()) ~ "W/out this week",
                                            lubridate::month(final_date) == lubridate::month(Sys.Date()) ~ "W/out this month",
                                            TRUE ~ "The Rest"))

# GEX for the Calls
db_option_chain_enhance_Calls <- db_option_chain_final %>% dplyr::filter(type == "Calls")

GEX_Calls <- greeks(bscall(s  = db_option_chain_enhance_Calls$Spot_Price,
                           k  = db_option_chain_enhance_Calls$Strike,
                           v  = db_option_chain_enhance_Calls$IV,
                           r  = risk_free_rate/100,
                           tt = db_option_chain_enhance_Calls$time_expiration_years,
                           d  = div_yield/100), complete = TRUE) %>%
  dplyr::select(k, s, Gamma) %>%
  dplyr::mutate(Date = db_option_chain_enhance_Calls$final_date,
                OI   = db_option_chain_enhance_Calls %>% dplyr::filter(type == "Calls") %>% dplyr::select(OI) %>% pluck(1), 
                type = "Calls",
                GEX  = Gamma * Multiplier * OI * s^2 * 0.01,
                k    = k * db_option_chain_enhance_Calls$Price_Ratios)

# GEX for the Puts
db_option_chain_enhance_Puts <- db_option_chain_final %>% dplyr::filter(type == "Puts")

GEX_Puts <- greeks(bsput(s  = db_option_chain_enhance_Puts$Spot_Price,
                         k  = db_option_chain_enhance_Puts$Strike,
                         v  = db_option_chain_enhance_Puts$IV,
                         r  = risk_free_rate/100,
                         tt = db_option_chain_enhance_Puts$time_expiration_years,
                         d  = div_yield/100), complete = TRUE) %>%
  dplyr::select(k, s, Gamma) %>%
  dplyr::mutate(Date = db_option_chain_enhance_Puts$final_date,
                OI   = db_option_chain_enhance_Puts %>% dplyr::filter(type == "Puts") %>% dplyr::select(OI) %>% pluck(1), 
                type = "Puts",
                GEX  = Gamma * Multiplier * OI * s^2 * 0.01 * -1,
                k    = k * db_option_chain_enhance_Puts$Price_Ratios)

# Combining both DB of GEX
db_GEX <- GEX_Puts %>% rbind(GEX_Calls)

# Netting GEX across all the strikes
p <- db_GEX %>%
  dplyr::select(k, GEX) %>%
  dplyr::group_by(k) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  dplyr::filter(k > SPX_Price*0.80 & k < SPX_Price*1.20) %>%
  purrr::set_names(c("Strike", "Gamma Exposure")) %>%
  ggplot(aes(x = Strike, y = `Gamma Exposure`)) +
  geom_bar(stat = "identity") +
  geom_vline(xintercept = SPX_Price, linetype = "dotted", color = "blue", size = 0.9) +
  scale_y_continuous(labels = scales::dollar_format()) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  labs(title    = str_glue("Total Gamma: {dollar_format()(sum(db_GEX$GEX)/1000000000)} Billions per 1% move in the SP500"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {ticker_label})."), 
       caption  = "Data Source: Yahoo Finance",
       x = "Strike Price",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal()

p

ggsave("GEX_vs_Strikes.png", plot = p, device = "png", path = "Plots - GEX Yahoo/")

# Netting GEX across all the dates
p <- db_GEX %>%
  dplyr::select(Date, GEX) %>%
  dplyr::group_by(Date) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  purrr::set_names(c("Date", "Gamma Exposure")) %>%
  ggplot(aes(x = Date, y = `Gamma Exposure`)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title    = str_glue("Total Gamma by Expiration Date"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {ticker_label})."), 
       caption  = "Data Source: Yahoo Finance",
       x = "Expiration Date",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal()

p

ggsave("GEX_vs_All_Expirations.png", plot = p, device = "png", path = "Plots - GEX Yahoo/")

# GEX (Next Two Months)
p <- db_GEX %>%
  dplyr::select(Date, GEX) %>%
  dplyr::group_by(Date) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  dplyr::mutate(Month = lubridate::month(Date),
                Month_Filter = ifelse(Date <= Sys.Date() + 60, "Yes", "No")) %>%
  dplyr::filter(Month_Filter == "Yes") %>%
  dplyr::select(Date, GEX_NET) %>%
  purrr::set_names(c("Date", "Gamma Exposure")) %>%
  ggplot(aes(x = Date, y = `Gamma Exposure`)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title    = str_glue("Total Gamma by Expiration Date - Next Two Months"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {ticker_label})."), 
       caption  = "Data Source: Yahoo Finance",
       x = "Expiration Date",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal()

p

ggsave("GEX_vs_Next_Two_Months.png", plot = p, device = "png", path = "Plots - GEX Yahoo/")

# GEX across Strikes and option type
Colour <- c(Calls = "green", Puts = "red")

p <- db_GEX %>%
  dplyr::select(k, type, GEX) %>%
  dplyr::group_by(k, type) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  purrr::set_names(c("Strike", "Type", "Gamma Exposure")) %>%
  dplyr::filter(Strike > SPX_Price*0.80 & Strike < SPX_Price*1.20) %>%
  ggplot(aes(x = Strike, y = `Gamma Exposure`, fill = Type)) +
  geom_vline(xintercept = SPX_Price, linetype = "dotted", color = "blue", size = 0.9) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values=Colour) +
  scale_y_continuous(labels = scales::dollar_format()) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  labs(title    = str_glue("Total Gamma Exposure: {dollar_format()(sum(db_GEX$GEX)/1000000000)} Billions per 1% move in the SP500"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {ticker_label})."), 
       caption  = "Data Source: Yahoo Finance",
       x = "Strike Price",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal() +
  theme(legend.title = element_blank())

p

ggsave("GEX_vs_Option_Types.png", plot = p, device = "png", path = "Plots - GEX Yahoo/")

# Calculating the Gamma Exposure Profile
GEX_blocks     <- c("All expirations", db_option_chain_final$Expiration_Date %>% unique() %>% head(n = 2))
db_GEX_Profile <- NULL 

for(blocks in GEX_blocks){ # blocks <- "All expirations"
  
  # Filtering
  if(blocks == "All expirations"){
    db_Option_Chain_New <- db_option_chain_final
    block_Label <- "All expirations"
  }else if(blocks == "W/out this week"){
    db_Option_Chain_New <- db_option_chain_final %>% dplyr::filter(!Expiration_Date %in% c("All expirations", "W/out this week"))
    block_Label <- "W/out this week"
  }else{
    db_Option_Chain_New <- db_option_chain_final %>% dplyr::filter(!Expiration_Date %in% c("All expirations", "W/out this week", "W/out this month"))
    block_Label <- "W/out this month"
  }
  
  # Setting the Delta in price
  Spot_Steps <- seq(-20, 20, 0.1)
  
  for(new_step in Spot_Steps){ # new_step <- 0
    
    # GEX for the Calls
    db_option_chain_enhance_Calls <- db_Option_Chain_New %>% dplyr::filter(type == "Calls")
    
    GEX_Calls <- greeks(bscall(s  = db_option_chain_enhance_Calls$Spot_Price*(1 + new_step/100),
                               k  = db_option_chain_enhance_Calls$Strike,
                               v  = db_option_chain_enhance_Calls$IV,
                               r  = risk_free_rate/100,
                               tt = db_option_chain_enhance_Calls$time_expiration_years,
                               d  = div_yield/100), complete = TRUE) %>%
      dplyr::select(k, s, Gamma) %>%
      dplyr::mutate(Date = db_option_chain_enhance_Calls$final_date,
                    OI   = db_option_chain_enhance_Calls %>% dplyr::filter(type == "Calls") %>% dplyr::select(OI) %>% pluck(1), 
                    type = "Calls",
                    GEX  = Gamma * Multiplier * OI * s^2 * 0.01)
    
    # GEX for the Puts
    db_option_chain_enhance_Puts <- db_Option_Chain_New %>% dplyr::filter(type == "Puts")
    
    GEX_Puts <- greeks(bsput(s  = db_option_chain_enhance_Puts$Spot_Price*(1 + new_step/100),
                             k  = db_option_chain_enhance_Puts$Strike,
                             v  = db_option_chain_enhance_Puts$IV,
                             r  = risk_free_rate/100,
                             tt = db_option_chain_enhance_Puts$time_expiration_years,
                             d  = div_yield/100), complete = TRUE) %>%
      dplyr::select(k, s, Gamma) %>%
      dplyr::mutate(Date = db_option_chain_enhance_Puts$final_date,
                    OI   = db_option_chain_enhance_Puts %>% dplyr::filter(type == "Puts") %>% dplyr::select(OI) %>% pluck(1), 
                    type = "Puts",
                    GEX  = Gamma * Multiplier * OI * s^2 * 0.01 * -1)
    
    # Combining all the GEX DB
    db_GEX_Spot <- GEX_Puts %>% rbind(GEX_Calls)
    
    # Saving the calculations in a provisional Dataframe
    db_GEX_Profile_prov <- data.frame(Spot_Change = new_step,
                                      GEX         = sum(db_GEX_Spot$GEX),
                                      Scenario    = block_Label)
    
    # Accumulating 
    db_GEX_Profile <- db_GEX_Profile %>% rbind(db_GEX_Profile_prov)
  }
}

Gamma_Flip <- db_GEX_Profile %>%
  dplyr::filter(Scenario == "All expirations") %>%
  dplyr::mutate(Spot_Change = lowess(Spot_Change, GEX, f = 1/10) %>% pluck(1),
                GEX         = (lowess(Spot_Change, GEX, f = 1/10) %>% pluck(2))/1000000000,
                Flip = ifelse(dplyr::lead(GEX > 0) & GEX < 0, "Yes", "No")) %>%
  dplyr::filter(Flip == "Yes") %>%
  dplyr::select(Spot_Change) %>%
  pull(1) %>% first()

# GEX Profile applying locally weighted scatterplot smoothing (removing the noice of the calculations)
p <- db_GEX_Profile %>%
  dplyr::filter(Scenario == "All expirations") %>%
  dplyr::mutate(Spot_Change = lowess(Spot_Change, GEX, f = 1/10) %>% pluck(1),
                GEX         = (lowess(Spot_Change, GEX, f = 1/10) %>% pluck(2))/1000000000) %>%
  ggplot(aes(Spot_Change/100, GEX)) + 
  geom_rect(inherit.aes = TRUE,
            aes(xmin = -Inf, xmax = -0.015, ymin = -Inf, ymax = +Inf), 
            fill = 'red', alpha = 0.005) +
  geom_rect(inherit.aes = TRUE,
            aes(xmin = +0.015, xmax = +Inf, ymin = -Inf, ymax = +Inf), 
            fill = 'green', alpha = 0.005) +
  geom_rect(inherit.aes = TRUE,
            aes(xmin = -0.015, xmax = +0.015, ymin = -Inf, ymax = +Inf), 
            fill = 'orange', alpha = 0.005) +
  geom_vline(xintercept = c(0, Gamma_Flip/100), linetype = "dotted", color = c("steelblue", "red"), size = 0.9) +
  geom_hline(yintercept = c(sum(db_GEX$GEX)/1000000000, 0), linetype = "dotted", color = c("steelblue", "red"), size = 0.9) +
  geom_line(size = 1.3, colour = "black") +
  labs(title    = str_glue("Total Gamma Exposure Profile of the SP500. All Expirations."),
       subtitle = str_glue("Gamma Flip (red dotted line) at {round(Gamma_Flip, digits = 2)}% of current price (meaning at: {round(SPX_Price*(1+Gamma_Flip/100), digits = 2)}). This study is considering: {ticker_label}."),
       caption  = "Data Source: Yahoo Finance",
       x = "Change in Spot Price",
       y = "Spot Gamma Exposure (Billions)") +
  scale_y_continuous(labels = scales::dollar_format(),
                     breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = scales::pretty_breaks(n = 10),
                     sec.axis = sec_axis(trans = ~ . * SPX_Price + SPX_Price, name = "SPX Price", breaks = scales::pretty_breaks(n = 10))) +
  theme(legend.title = element_blank())  

p

ggsave("GEX_Profile_All_Expirations.png", plot = p, device = "png", path = "Plots - GEX Yahoo/", width = 10, height = 7, units = "in")

# Different Scenarios of GEX
p <- db_GEX_Profile %>%
  dplyr::group_by(Scenario) %>%
  dplyr::mutate(Spot_Change = lowess(Spot_Change, GEX, f = 1/10) %>% pluck(1),
                GEX         = (lowess(Spot_Change, GEX, f = 1/10) %>% pluck(2))/1000000000) %>%
  ggplot(aes(Spot_Change/100, GEX, colour = Scenario, group = Scenario)) + 
  scale_color_viridis(discrete = TRUE) +
  geom_vline(xintercept = c(0, Gamma_Flip/100), linetype = "dotted", color = c("steelblue", "red"), size = 0.9) +
  geom_hline(yintercept = c(sum(db_GEX$GEX)/1000000000, 0), linetype = "dotted", color = c("steelblue", "red"), size = 0.9) +
  geom_line(size = 1.3) +
  labs(title    = str_glue("Total Gamma Exposure Profile of the SP500. Scenario Analysis."),
       subtitle = str_glue("Gamma Flip - All Expirations - (red dotted line) at {round(Gamma_Flip, digits = 2)}% of current price (meaning at: {round(SPX_Price*(1+Gamma_Flip/100), digits = 2)}). This study is considering: {ticker_label}."),  
       caption  = "Data Source: Yahoo Finance",
       x = "Change in Spot Price",
       y = "Spot Gamma Exposure (Billions)") +
  scale_y_continuous(labels = scales::dollar_format(),
                     breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = scales::pretty_breaks(n = 10),
                     sec.axis = sec_axis(trans = ~ . * SPX_Price + SPX_Price, name = "SPX Price", breaks = scales::pretty_breaks(n = 10))) +
  theme(legend.title = element_blank()) +
  theme_minimal()

p

ggsave("GEX_Profile_Scenarios.png", plot = p, device = "png", path = "Plots - GEX Yahoo/", width = 10, height = 7, units = "in") 

# Getting the VIX
db_Volatility <- tq_get("^VIX",
                        from = Sys.Date() - lubridate::years(2),
                        to   = Sys.Date(),
                        get  = "stock.prices",
                        complete_cases = TRUE) %>%
  dplyr::select(date, adjusted) %>%
  left_join(tq_get("SPY",
                   from = Sys.Date() - lubridate::years(2),
                   to   = Sys.Date(),
                   get  = "stock.prices",
                   complete_cases = TRUE) %>%
              dplyr::select(date, adjusted) %>%
              dplyr::mutate(Ret      = TTR::ROC(adjusted, n = 1, type = "discrete"),
                            Real_Vol = roll::roll_sd(Ret, width = 22)*100*sqrt(252)) %>%
              dplyr::select(date, Real_Vol), by = "date") %>%
  na.omit() %>%
  dplyr::mutate(Spread = adjusted - Real_Vol) %>%
  purrr::set_names(c("Date", "Implied Volatility", "Realized Volatility", "Spread"))

p_volatilites <- db_Volatility %>%
  dplyr::select(Date, `Implied Volatility`, `Realized Volatility`) %>%
  pivot_longer(names_to = "Type", values_to = "Volatility", -Date) %>%
  ggplot(aes(x = Date, y = Volatility/100, colour = Type)) +
  geom_line(size = 0.7) +
  theme_bw() +
  labs(title    = "VIX vs Realized SP500 short-term Volatility",
       subtitle = "Volatility behavior of the SP500",
       caption  = "",
       x        = "",
       y        = "") +
  scale_y_continuous(labels = scales::percent) + 
  theme(legend.title = element_blank()) +
  theme(legend.position="bottom")

p_spread <- db_Volatility %>%
  dplyr::select(Date, Spread) %>%
  dplyr::mutate(Mean_Vol = roll::roll_mean(Spread, width = 50)) %>%
  na.omit() %>%
  purrr::set_names(c("Date", "Spread", "Mean")) %>%
  ggplot() +
  geom_line(aes(x = Date, y = Spread/100), size = 0.7) +
  geom_line(aes(x = Date, y = Mean/100), size = 1.1, colour = "red") +
  theme_bw() +
  labs(title    = "Volatility Spread",
       subtitle = "How expensive/cheap is the current volatility?",
       caption  = "",
       x        = "",
       y        = "") +
  scale_y_continuous(labels = scales::percent) + 
  theme(legend.title = element_blank())

p_vix <- db_Volatility %>%
  dplyr::select(Date, `Implied Volatility`) %>%
  purrr::set_names(c("Date", "IV")) %>%
  bind_rows(data.frame(Date = Sys.Date(),
                       IV   = getQuote("^VIX") %>% dplyr::select(Last) %>% pull(1))) %>%
  ggplot(aes(x = Date, y = IV/100)) +
  geom_line(size = 0.7) +
  geom_smooth(method = 'loess', formula = 'y ~ x') +
  theme_bw() +
  labs(title    = "CBOE Volatility Index",
       subtitle = "Short-term trend of the Implied Volatility",
       caption  = "Data Source: Yahoo Finance.",
       x        = "",
       y        = "") +
  scale_y_continuous(labels = scales::percent) + 
  theme(legend.title = element_blank()) +
  geom_hline(yintercept = 0.25, linetype = "dashed", color = "red", size = 1.2)

grid.arrange(p_volatilites, arrangeGrob(p_spread, p_vix, ncol=2), nrow = 2)

ggsave("VIX_Analysis.png", plot = grid.arrange(p_volatilites, arrangeGrob(p_spread, p_vix, ncol=2), nrow = 2), path = "Plots - GEX Yahoo/", scale = 1, dpi = 320, width = 30, height = 20, units = "cm")

# Extracting the VIX Structure from the Option Chain
MMS_First_Criteria  <- 0.95
MMS_Second_Criteria <- 1.05

ATM_Price         <- db_Ratios %>% dplyr::filter(Symbol == "^SPX") %>% dplyr::select(Spot_Price) %>% pull(1)
MoneynessFC_Price <- ATM_Price*MMS_First_Criteria
MoneynessSC_Price <- ATM_Price*MMS_Second_Criteria

p <- db_option_chain_final %>% 
  dplyr::select(final_date, type, IV, Strike) %>%
  dplyr::filter(type == "Puts" & final_date >= Sys.Date()) %>%
  dplyr::mutate(final_date = final_date %>% as.Date()) %>%
  dplyr::mutate(VST = ifelse(dplyr::lead(Strike, n = 1) > ATM_Price & dplyr::lag(Strike, n = 1) < ATM_Price, "ATM", 
                             ifelse(dplyr::lead(Strike, n = 1) > MoneynessFC_Price & dplyr::lag(Strike, n = 1) < MoneynessFC_Price, str_glue("MM{MMS_First_Criteria*100}"), 
                                    ifelse(dplyr::lead(Strike, n = 1) > MoneynessSC_Price & dplyr::lag(Strike, n = 1) < MoneynessSC_Price, str_glue("MM{MMS_Second_Criteria*100}"), "")))) %>% 
  dplyr::filter(VST != "") %>%
  dplyr::select(final_date, IV, VST) %>%
  dplyr::group_by(final_date, VST) %>%
  dplyr::summarise(Mean_IV = mean(IV %>% as.numeric()), .groups = "drop") %>%
  dplyr::mutate(VST = case_when(VST == str_glue("MM{MMS_First_Criteria*100}") ~ str_glue("Moneyness {MMS_First_Criteria*100}%"),
                                VST == str_glue("MM{MMS_Second_Criteria*100}") ~ str_glue("Moneyness {MMS_Second_Criteria*100}%"),
                                TRUE ~ VST)) %>%
  dplyr::group_by(VST) %>%
  dplyr::mutate(Mean_IV = (lowess(final_date, Mean_IV, f = 1/2) %>% pluck(2))) %>%
  ggplot(aes(x = final_date, y = Mean_IV, colour = VST)) +
  geom_line(size = 0.9) +
  labs(title    = "Implied Volatility Structure",
       subtitle = "Smoothed data extracted from the Option Chain",
       caption  = "Data Source: Yahoo Finance.",
       x        = "",
       y        = "Implied Volatility") +
  scale_y_continuous(labels = scales::percent) +
  theme(legend.title = element_blank(),
        legend.position = "bottom")

p

ggsave("vix_structure.png", path = "Plots - GEX Yahoo/", plot = p, scale = 1, dpi = 320, width = 30, height = 20, units = "cm")
