# Instructions #
# Step 1: click run - Enjoy!!!!
# Step 2: all the charts generated by this scrip will be saved in the Plots - GEX Yahoo Folder
# Tip: Run this script 1 hour after the market is open (you will get better results)
# Tip: Never run this script after the market is close (the numbers wont make any sense)
# Tip: make sure Local Variables dataframe is correct (this is the main source of inputs)

# Global Variables
options(scipen = 999)
options(dplyr.summarise.inform = FALSE)

# Getting the functions
source(file = "00_scripts/Libraries.R")

# Loading the functions
libraries()

# Deleting all the files from Plots - GEX
do.call(file.remove, list(list.files("Plots - GEX Yahoo/", full.names = TRUE)))

# Local Variables
Ticker           <- c("^SPX", "^XSP", "SPY") # Yahoo Finance Format
Price_Ratio      <- c(1, 10, 10)
Multiplier       <- c(100, 100, 100)
Option_Type      <- c("European", "European", "American")
Chart_label      <- "SPX, XSP and SPY"
Reference_Ticker <- "^SPX"
environment_r    <- "EU" # Could be EU or US

# Getting the Risk Free Rate (Using the 10 Year Gov Bong Yield as a proxy)
risk_free_rate <- getSymbols(Symbols = "DGS10", src = "FRED", auto.assign = FALSE) %>%
  tail(n = 1) %>%
  as.data.frame() %>%
  pull(1)

# Defining the dataframe with tickers and tickers information
db_Tickers <- data.frame(Ticker         = Ticker,
                         Multiplier     = Multiplier, 
                         Option_Type    = Option_Type,
                         risk_free_rate = risk_free_rate/100, 
                         Price_Ratio    = Price_Ratio) %>%   # By how much you need to multiply the price to put it at the same level as the Reference Ticker
  dplyr::mutate(Spot_Price = getQuote(Ticker)$Last,
                div_yield  = getQuote(Ticker, what = yahooQF("Dividend Yield"))[2] %>% pull(1)) %>% # Dividend Yield of the underlying
  replace(is.na(.), 0)

# Setting the years for the Option Chain
sYear <- lubridate::year(Sys.Date())
eYear <- lubridate::year(Sys.Date()) + 1

# Getting the Option Chain from Yahoo Finance
option_chain_yahoo <- NULL

for(Ticker_Yahoo in db_Tickers$Ticker){ # Ticker_Yahoo <- "SPY"
  db_option <- getOptionChain(Ticker_Yahoo, src = "yahoo", Exp = str_glue("{sYear}/{eYear}")) %>%
    unlist(recursive = FALSE) %>%
    enframe() %>%
    unnest(cols = c(value)) %>%
    dplyr::mutate(Symbol = Ticker_Yahoo)
  
  option_chain_yahoo <- bind_rows(option_chain_yahoo, db_option)
}

# Fixing and Enhancing the database
option_chain_yahoo_enhanced <- option_chain_yahoo %>%
  left_join(db_Tickers, by = c("Symbol" = "Ticker")) %>%
  dplyr::mutate(Symbol = case_when(Symbol == "^SPX" ~ "SPX", 
                                   Symbol == "^XSP" ~ "XSP",
                                   TRUE ~ Symbol)) %>%
  dplyr::filter(Expiration >= Sys.Date())

  # Extracting the type of Option
  opt_type <- c()
  for(i in 1:nrow(option_chain_yahoo_enhanced)){ # i <- 1
    
    # Selecting the name column
    name_tag <- option_chain_yahoo_enhanced$name[i]
    
    # Getting the length of that name
    name_length <- nchar(name_tag)
    
    # Getting the option type
    opt_type <- c(opt_type, substr(name_tag, 14, name_length))
  }

# Adding the Option Type
option_chain_yahoo_enhanced <- option_chain_yahoo_enhanced %>%
  dplyr::mutate(type = opt_type)

# Adding the Current Prices and Time to Expiration (in Years)
db_option_chain_final <- option_chain_yahoo_enhanced %>%
  dplyr::mutate(type = case_when(type == "calls" ~ "Calls",
                                 TRUE ~ "Puts"),
                time_expiration_years = (((Expiration %>% as.Date()) - Sys.Date()) %>% as.numeric())/365,
                time_expiration_years = case_when(time_expiration_years == 0 ~ 1, TRUE ~ time_expiration_years), # For 0 DTE options, I'm setting DTE = 1 day, otherwise they get excluded
                Expiration_Date = case_when(lubridate::week(Expiration) == lubridate::week(Sys.Date()) ~ "W/out this week",
                                            lubridate::month(Expiration) == lubridate::month(Sys.Date()) ~ "W/out this month",
                                            TRUE ~ "The Rest"))

# GEX for the Calls
db_option_chain_enhance_Calls <- db_option_chain_final %>% 
  dplyr::filter(type == "Calls") %>% 
  dplyr::select(Spot_Price, Strike, IV, risk_free_rate, time_expiration_years, div_yield, Expiration, OI, Multiplier, Price_Ratio, type) %>%
  replace(is.na(.), 0)

GEX_Calls <- greeks(bscall(s  = db_option_chain_enhance_Calls$Spot_Price,
                           k  = db_option_chain_enhance_Calls$Strike,
                           v  = db_option_chain_enhance_Calls$IV,
                           r  = db_option_chain_enhance_Calls$risk_free_rate,
                           tt = db_option_chain_enhance_Calls$time_expiration_years,
                           d  = db_option_chain_enhance_Calls$div_yield), complete = TRUE) %>%
  dplyr::select(k, s, Gamma) %>%
  dplyr::mutate(Date = db_option_chain_enhance_Calls$Expiration,
                OI   = db_option_chain_enhance_Calls %>% dplyr::filter(type == "Calls") %>% dplyr::select(OI) %>% pluck(1), 
                type = "Calls",
                GEX  = +1 * Gamma * db_option_chain_enhance_Calls$Multiplier * OI * s^2 * 0.01,
                k    = k * db_option_chain_enhance_Calls$Price_Ratio)

# GEX for the Puts
db_option_chain_enhance_Puts <- db_option_chain_final %>% 
  dplyr::filter(type == "Puts") %>% 
  dplyr::select(Spot_Price, Strike, IV, risk_free_rate, time_expiration_years, div_yield, Expiration, OI, Multiplier, Price_Ratio, type) %>%
  replace(is.na(.), 0)

GEX_Puts <- greeks(bsput(s  = db_option_chain_enhance_Puts$Spot_Price,
                         k  = db_option_chain_enhance_Puts$Strike,
                         v  = db_option_chain_enhance_Puts$IV,
                         r  = db_option_chain_enhance_Puts$risk_free_rate,
                         tt = db_option_chain_enhance_Puts$time_expiration_years,
                         d  = db_option_chain_enhance_Puts$div_yield), complete = TRUE) %>%
  dplyr::select(k, s, Gamma) %>%
  dplyr::mutate(Date = db_option_chain_enhance_Puts$Expiration,
                OI   = db_option_chain_enhance_Puts %>% dplyr::filter(type == "Puts") %>% dplyr::select(OI) %>% pluck(1), 
                type = "Puts",
                GEX  = -1 * Gamma * db_option_chain_enhance_Puts$Multiplier * OI * s^2 * 0.01,
                k    = k * db_option_chain_enhance_Puts$Price_Ratio)

# Combining both DB of GEX
db_GEX <- GEX_Puts %>% rbind(GEX_Calls)

# Defining the Price of the Reference Ticker
Reference_Ticker_Price <- db_Tickers %>%
  dplyr::filter(Ticker == Reference_Ticker) %>%
  dplyr::select(Spot_Price) %>%
  pull(1)

# Netting GEX across all the strikes
p <- db_GEX %>%
  dplyr::select(k, GEX) %>%
  dplyr::group_by(k) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  dplyr::filter(k > Reference_Ticker_Price*0.80 & k < Reference_Ticker_Price*1.20) %>%
  purrr::set_names(c("Strike", "Gamma Exposure")) %>%
  ggplot(aes(x = Strike, y = `Gamma Exposure`)) +
  geom_bar(stat = "identity") +
  geom_vline(xintercept = Reference_Ticker_Price, linetype = "dotted", color = "blue", size = 0.9) +
  scale_y_continuous(labels = scales::dollar_format()) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  labs(title    = str_glue("Total Gamma: {dollar_format()(sum(db_GEX$GEX)/1000000000)} Billions per 1% move in the SP500"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {Chart_label})."), 
       caption  = "Data Source: Yahoo Finance",
       x = "Strike Price",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal()

p

ggsave("GEX_vs_Strikes.png", plot = p, device = "png", path = "Plots - GEX Yahoo/")

# Netting GEX across all the dates
p <- db_GEX %>%
  dplyr::select(Date, GEX) %>%
  dplyr::group_by(Date) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  purrr::set_names(c("Date", "Gamma Exposure")) %>%
  ggplot(aes(x = Date, y = `Gamma Exposure`)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title    = str_glue("Total Gamma by Expiration Date"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {Chart_label})."), 
       caption  = "Data Source: Yahoo Finance",
       x = "Expiration Date",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal()

p

ggsave("GEX_vs_All_Expirations.png", plot = p, device = "png", path = "Plots - GEX Yahoo/")

# GEX (Next Two Months)
p <- db_GEX %>%
  dplyr::select(Date, GEX) %>%
  dplyr::group_by(Date) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  dplyr::mutate(Month = lubridate::month(Date),
                Month_Filter = ifelse(Date <= Sys.Date() + 60, "Yes", "No")) %>%
  dplyr::filter(Month_Filter == "Yes") %>%
  dplyr::select(Date, GEX_NET) %>%
  purrr::set_names(c("Date", "Gamma Exposure")) %>%
  ggplot(aes(x = Date, y = `Gamma Exposure`)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title    = str_glue("Total Gamma by Expiration Date - Next Two Months"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {Chart_label})."), 
       caption  = "Data Source: Yahoo Finance",
       x = "Expiration Date",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal()

p

ggsave("GEX_vs_Next_Two_Months.png", plot = p, device = "png", path = "Plots - GEX Yahoo/")

# GEX across Strikes and option type
p <- db_GEX %>%
  dplyr::select(k, type, GEX) %>%
  dplyr::group_by(k, type) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  purrr::set_names(c("Strike", "Type", "Gamma Exposure")) %>%
  dplyr::filter(Strike > Reference_Ticker_Price*0.80 & Strike < Reference_Ticker_Price*1.20) %>%
  ggplot(aes(x = Strike, y = `Gamma Exposure`, fill = Type)) +
  geom_vline(xintercept = Reference_Ticker_Price, linetype = "dotted", color = "blue", size = 0.9) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c(Calls = "green", Puts = "red")) +
  scale_y_continuous(labels = scales::dollar_format()) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  labs(title    = str_glue("Total Gamma Exposure: {dollar_format()(sum(db_GEX$GEX)/1000000000)} Billions per 1% move in the SP500"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {Chart_label})."), 
       caption  = "Data Source: Yahoo Finance",
       x = "Strike Price",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal() +
  theme(legend.title = element_blank())

p

ggsave("GEX_vs_Option_Types.png", plot = p, device = "png", path = "Plots - GEX Yahoo/")

# Calculating the Gamma Exposure Profile
GEX_blocks     <- c("All expirations", db_option_chain_final$Expiration_Date %>% unique() %>% head(n = 2))
db_GEX_Profile <- NULL 

for(blocks in GEX_blocks){ # blocks <- "All expirations"
  
  # Filtering
  if(blocks == "All expirations"){
    db_Option_Chain_New <- db_option_chain_final
    block_Label <- "All expirations"
  }else if(blocks == "W/out this week"){
    db_Option_Chain_New <- db_option_chain_final %>% dplyr::filter(!Expiration_Date %in% c("All expirations", "W/out this week"))
    block_Label <- "W/out this week"
  }else{
    db_Option_Chain_New <- db_option_chain_final %>% dplyr::filter(!Expiration_Date %in% c("All expirations", "W/out this week", "W/out this month"))
    block_Label <- "W/out this month"
  }
  
  # Setting the Delta in price
  Spot_Steps <- seq(-20, 20, 0.1)
  
  for(new_step in Spot_Steps){ # new_step <- 0
    
    # GEX for the Calls
    db_option_chain_enhance_Calls <- db_Option_Chain_New %>% dplyr::filter(type == "Calls")
    
    GEX_Calls <- greeks(bscall(s  = db_option_chain_enhance_Calls$Spot_Price*(1 + new_step/100),
                               k  = db_option_chain_enhance_Calls$Strike,
                               v  = db_option_chain_enhance_Calls$IV,
                               r  = db_option_chain_enhance_Calls$risk_free_rate,
                               tt = db_option_chain_enhance_Calls$time_expiration_years,
                               d  = db_option_chain_enhance_Calls$div_yield), complete = TRUE) %>%
      dplyr::select(k, s, Gamma) %>%
      dplyr::mutate(Date = db_option_chain_enhance_Calls$final_date,
                    OI   = db_option_chain_enhance_Calls %>% dplyr::filter(type == "Calls") %>% dplyr::select(OI) %>% pluck(1), 
                    type = "Calls",
                    GEX  = +1 * Gamma * db_option_chain_enhance_Calls$Multiplier * OI * s^2 * 0.01,
                    k    = k * db_option_chain_enhance_Calls$Price_Ratio)
    
    # GEX for the Puts
    db_option_chain_enhance_Puts <- db_Option_Chain_New %>% dplyr::filter(type == "Puts")
    
    GEX_Puts <- greeks(bsput(s  = db_option_chain_enhance_Puts$Spot_Price*(1 + new_step/100),
                             k  = db_option_chain_enhance_Puts$Strike,
                             v  = db_option_chain_enhance_Puts$IV,
                             r  = db_option_chain_enhance_Puts$risk_free_rate,
                             tt = db_option_chain_enhance_Puts$time_expiration_years,
                             d  = db_option_chain_enhance_Puts$div_yield), complete = TRUE) %>%
      dplyr::select(k, s, Gamma) %>%
  dplyr::mutate(Date = db_option_chain_enhance_Puts$final_date,
                OI   = db_option_chain_enhance_Puts %>% dplyr::filter(type == "Puts") %>% dplyr::select(OI) %>% pluck(1), 
                type = "Puts",
                GEX  = -1 * Gamma * db_option_chain_enhance_Puts$Multiplier * OI * s^2 * 0.01,
                k    = k * db_option_chain_enhance_Puts$Price_Ratio)
    
    # Combining all the GEX DB
    db_GEX_Spot <- GEX_Puts %>% rbind(GEX_Calls)
    
    # Saving the calculations in a provisional Dataframe
    db_GEX_Profile_prov <- data.frame(Spot_Change = new_step,
                                      GEX         = sum(db_GEX_Spot$GEX),
                                      Scenario    = block_Label)
    
    # Accumulating 
    db_GEX_Profile <- db_GEX_Profile %>% rbind(db_GEX_Profile_prov)
  }
}

Gamma_Flip <- db_GEX_Profile %>%
  dplyr::filter(Scenario == "All expirations") %>%
  dplyr::mutate(Spot_Change = lowess(Spot_Change, GEX, f = 1/10) %>% pluck(1),
                GEX         = (lowess(Spot_Change, GEX, f = 1/10) %>% pluck(2))/1000000000,
                Flip = ifelse(dplyr::lead(GEX > 0) & GEX < 0, "Yes", "No")) %>%
  dplyr::filter(Flip == "Yes") %>%
  dplyr::select(Spot_Change) %>%
  pull(1) %>% first()

# GEX Profile applying locally weighted scatterplot smoothing (removing the noice of the calculations)
p <- db_GEX_Profile %>%
  dplyr::filter(Scenario == "All expirations") %>%
  dplyr::mutate(Spot_Change = lowess(Spot_Change, GEX, f = 1/10) %>% pluck(1),
                GEX         = (lowess(Spot_Change, GEX, f = 1/10) %>% pluck(2))/1000000000) %>%
  ggplot(aes(Spot_Change/100, GEX)) + 
  geom_rect(inherit.aes = TRUE,
            aes(xmin = -Inf, xmax = -0.015, ymin = -Inf, ymax = +Inf), 
            fill = 'red', alpha = 0.005) +
  geom_rect(inherit.aes = TRUE,
            aes(xmin = +0.015, xmax = +Inf, ymin = -Inf, ymax = +Inf), 
            fill = 'green', alpha = 0.005) +
  geom_rect(inherit.aes = TRUE,
            aes(xmin = -0.015, xmax = +0.015, ymin = -Inf, ymax = +Inf), 
            fill = 'orange', alpha = 0.005) +
  geom_vline(xintercept = c(0, Gamma_Flip/100), linetype = "dotted", color = c("steelblue", "red"), size = 0.9) +
  geom_hline(yintercept = c(sum(db_GEX$GEX)/1000000000, 0), linetype = "dotted", color = c("steelblue", "red"), size = 0.9) +
  geom_line(size = 1.3, colour = "black") +
  labs(title    = str_glue("Total Gamma Exposure Profile of the SP500. All Expirations."),
       subtitle = str_glue("Gamma Flip (red dotted line) at {round(Gamma_Flip, digits = 2)}% of current price (meaning at: {round(Reference_Ticker_Price*(1+Gamma_Flip/100), digits = 2)}). This study is considering: {Chart_label}."),
       caption  = "Data Source: Yahoo Finance",
       x = "Change in Spot Price",
       y = "Spot Gamma Exposure (Billions)") +
  scale_y_continuous(labels = scales::dollar_format(),
                     breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = scales::pretty_breaks(n = 10),
                     sec.axis = sec_axis(trans = ~ . * Reference_Ticker_Price + Reference_Ticker_Price, name = "SPX Price", breaks = scales::pretty_breaks(n = 10))) +
  theme(legend.title = element_blank())  

p

ggsave("GEX_Profile_All_Expirations.png", plot = p, device = "png", path = "Plots - GEX Yahoo/", width = 15, height = 7, units = "in")

# Different Scenarios of GEX
p <- db_GEX_Profile %>%
  dplyr::group_by(Scenario) %>%
  dplyr::mutate(Spot_Change = lowess(Spot_Change, GEX, f = 1/10) %>% pluck(1),
                GEX         = (lowess(Spot_Change, GEX, f = 1/10) %>% pluck(2))/1000000000) %>%
  ggplot(aes(Spot_Change/100, GEX, colour = Scenario, group = Scenario)) + 
  scale_color_viridis(discrete = TRUE) +
  geom_vline(xintercept = c(0, Gamma_Flip/100), linetype = "dotted", color = c("steelblue", "red"), size = 0.9) +
  geom_hline(yintercept = c(sum(db_GEX$GEX)/1000000000, 0), linetype = "dotted", color = c("steelblue", "red"), size = 0.9) +
  geom_line(size = 1.3) +
  labs(title    = str_glue("Total Gamma Exposure Profile of the SP500. Scenario Analysis."),
       subtitle = str_glue("Gamma Flip - All Expirations - (red dotted line) at {round(Gamma_Flip, digits = 2)}% of current price (meaning at: {round(Reference_Ticker_Price*(1+Gamma_Flip/100), digits = 2)}). This study is considering: {Chart_label}."),  
       caption  = "Data Source: Yahoo Finance",
       x = "Change in Spot Price",
       y = "Spot Gamma Exposure (Billions)") +
  scale_y_continuous(labels = scales::dollar_format(),
                     breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = scales::pretty_breaks(n = 10),
                     sec.axis = sec_axis(trans = ~ . * Reference_Ticker_Price + Reference_Ticker_Price, name = "SPX Price", breaks = scales::pretty_breaks(n = 10))) +
  theme(legend.title = element_blank()) +
  theme_minimal()

p

ggsave("GEX_Profile_Scenarios.png", plot = p, device = "png", path = "Plots - GEX Yahoo/", width = 15, height = 7, units = "in") 

# Extracting the VIX Structure from the Option Chain
MMS_First_Criteria  <- 0.95
MMS_Second_Criteria <- 1.05

ATM_Price         <- Reference_Ticker_Price
MoneynessFC_Price <- ATM_Price*MMS_First_Criteria
MoneynessSC_Price <- ATM_Price*MMS_Second_Criteria

p <- db_option_chain_final %>% 
  dplyr::select(final_date, type, IV, Strike) %>%
  dplyr::filter(type == "Puts" & final_date >= Sys.Date()) %>%
  dplyr::mutate(final_date = final_date %>% as.Date()) %>%
  dplyr::mutate(VST = ifelse(dplyr::lead(Strike, n = 1) > ATM_Price & dplyr::lag(Strike, n = 1) < ATM_Price, "ATM", 
                             ifelse(dplyr::lead(Strike, n = 1) > MoneynessFC_Price & dplyr::lag(Strike, n = 1) < MoneynessFC_Price, str_glue("MM{MMS_First_Criteria*100}"), 
                                    ifelse(dplyr::lead(Strike, n = 1) > MoneynessSC_Price & dplyr::lag(Strike, n = 1) < MoneynessSC_Price, str_glue("MM{MMS_Second_Criteria*100}"), "")))) %>% 
  dplyr::filter(VST != "") %>%
  dplyr::select(final_date, IV, VST) %>%
  dplyr::group_by(final_date, VST) %>%
  dplyr::summarise(Mean_IV = mean(IV %>% as.numeric()), .groups = "drop") %>%
  dplyr::mutate(VST = case_when(VST == str_glue("MM{MMS_First_Criteria*100}") ~ str_glue("Moneyness {MMS_First_Criteria*100}%"),
                                VST == str_glue("MM{MMS_Second_Criteria*100}") ~ str_glue("Moneyness {MMS_Second_Criteria*100}%"),
                                TRUE ~ VST)) %>%
  dplyr::group_by(VST) %>%
  dplyr::mutate(Mean_IV = (lowess(final_date, Mean_IV, f = 1/2) %>% pluck(2))) %>%
  ggplot(aes(x = final_date, y = Mean_IV, colour = VST)) +
  geom_line(size = 0.9) +
  labs(title    = "Implied Volatility Structure",
       subtitle = "Smoothed data extracted from the Option Chain",
       caption  = "Data Source: Yahoo Finance.",
       x        = "",
       y        = "Implied Volatility") +
  scale_y_continuous(labels = scales::percent) +
  theme(legend.title = element_blank(),
        legend.position = "bottom")

p

ggsave("vix_structure.png", path = "Plots - GEX Yahoo/", plot = p, scale = 1, dpi = 320, width = 30, height = 20, units = "cm")
