# Instructions #
# Step 1: click run - Enjoy!!!!
# Step 2: all the charts generated by this scrip will be saved in the Plots - GEX Yahoo Folder
# Tip: Run this script 1 hour after the market is open (you will get better results)
# Tip: Never run this script after the market is close (the numbers wont make any sense)
# Tip: make sure Local Variables dataframe is correct (this is the main source of inputs)

# Global Variables
options(scipen = 999)
options(dplyr.summarise.inform = FALSE)

# Getting the functions
source(file = "00_scripts/Libraries.R")

# Deleting all the files from Plots - GEX
do.call(file.remove, list(list.files("Plots - GEX CBOE/", full.names = TRUE)))
do.call(file.remove, list(list.files("cboe_file/From Scraping//", full.names = TRUE)))

# Loading the functions
libraries()

# Starting the Timer
tictoc::tic()

# Local Variables
Ticker_CBOE      <- c("_SPX", "_XSP", "SPY") # The same names you used in the CBOE website
Ticker_YAHOO     <- c("^SPX", "^XSP", "SPY") # The same names you used in Yahoo
Price_Ratio      <- c(1, 10, 10)
Multiplier       <- c(100, 100, 100)
Option_Type      <- c("European", "European", "American")
Chart_label      <- "SPX, XSP and SPY"
Reference_Ticker <- "_SPX"

# Local Dataframes
db_Option_Chain_Combined <- NULL
db_prices_from_CBOE      <- NULL

# Getting the Risk Free Rate (Using the 10 Year Gov Bong Yield as a proxy)
risk_free_rate <- getSymbols(Symbols = "DGS10", src = "FRED", auto.assign = FALSE) %>%
  tail(n = 1) %>%
  as.data.frame() %>%
  pull(1)

# Defining the dataframe with tickers and tickers information
db_Tickers <- data.frame(Ticker_CBOE    = Ticker_CBOE,
                         Ticker_YAHOO   = Ticker_YAHOO,
                         Multiplier     = Multiplier, 
                         Option_Type    = Option_Type,
                         risk_free_rate = risk_free_rate/100, 
                         Price_Ratio    = Price_Ratio) %>%   # By how much you need to multiply the price to put it at the same level as the Reference Ticker
  dplyr::mutate(div_yield = getQuote(Ticker_YAHOO, what = yahooQF("Dividend Yield"))[2] %>% pull(1)) %>% # Dividend Yield of the underlying
  replace(is.na(.), 0)

# Function to download CBOE data
for(i in 1:nrow(db_Tickers)){ # i <- 1
  
  # Sleep for X sec (for multiple symbols to not get block be the CBOE website)
  Sys.sleep(runif(1, min = 5, max = 10) %>% round(digits = 0))
  
  tryCatch(
    expr = {
      # Printing status
      print(str_glue("Getting info from {db_Tickers$Ticker_CBOE[i]}"))
      
      # Downloading data from CBOE website
      str_glue("https://cdn.cboe.com/api/global/delayed_quotes/options/{db_Tickers$Ticker_CBOE[i]}.json") %>%
        read_json(simplifyVector = TRUE) %>%
        pluck("data", "options") %>%
        as.data.frame() %>%  
        dplyr::mutate(Ticker_CBOE = db_Tickers$Ticker_CBOE[i]) %>%
        left_join(db_Tickers, by = "Ticker_CBOE") %>%
        dplyr::mutate(Spot_Price   = getQuote(db_Tickers$Ticker_YAHOO[i])$Last,
                      expiry       = str_sub(option, -15, -10) %>% as.Date(format = "%y%m%d"),
                      opt_type     = str_sub(option, -9, -9),
                      strike       = paste0(str_sub(str_sub(option, -8, -1), -8, -4),".",str_sub(str_sub(option, -8, -1), -3, -1)) %>% as.numeric(),
                      days2Exp     = as.Date(expiry) - Sys.Date(),
                      Mid_price    = round((bid + ask)/2, 2),
                      Time_Process = Sys.time()) %>%
        saveRDS(str_glue("cboe_file/From Scraping/CBOE_Data_{db_Tickers$Ticker_CBOE[i]}.rds"))

    },
    error = function(e){ 
      print(str_glue("ERROR Getting info from {db_Tickers$Ticker_CBOE[i]}"))
    },
    warning = function(w){ 
      print(str_glue("ERROR Getting info from {db_Tickers$Ticker_CBOE[i]}"))
    }
  )
}

# Generating the Option Chain
acum_GEX <- NULL
for(CBOE_File in list.files("cboe_file/From Scraping/")){ # CBOE_File <- "CBOE_Data__SPX.rds"

  # Reading the data from the CBOE File (General Information)
  CBOE_General_Info <- readRDS(str_glue("cboe_file/From Scraping/{CBOE_File}"))

  # Saving the info of the spot price from the CBOE File
  db_prices_from_CBOE <- db_prices_from_CBOE %>%
    rbind(data.frame(Reference_Price = CBOE_General_Info$Spot_Price[1],
                     Ticker          = CBOE_General_Info$Ticker_CBOE[1]))
  
  # Extracting data from the Calls and calculating GEX
    # GEX - Calls
    db_Option_Chain_Calls <- CBOE_General_Info %>%
      dplyr::filter(opt_type == "C") %>%
      dplyr::select(expiry, iv, open_interest, strike, Spot_Price, days2Exp, Time_Process, div_yield, risk_free_rate, Multiplier, Price_Ratio) %>%
      dplyr::mutate(type      = "Calls",
                    days2Exp  = days2Exp %>% as.numeric(),
                    days2Exp  = case_when(days2Exp == 0 ~ 1/365, TRUE ~ days2Exp/365),
                    Scenario1 = case_when(lubridate::week(expiry)  == lubridate::week(Time_Process) ~ "This Week",
                                          TRUE ~ "Not This Week"),
                    Scenario2 = case_when(lubridate::month(expiry)  == lubridate::month(Time_Process) ~ "This Month",
                                          TRUE ~ "Not This Month"),
                    Scenario3 = "All Dates")
    
    # GEX Calculations
    GEX_Calls <- greeks(bscall(s  = db_Option_Chain_Calls$Spot_Price,
                               k  = db_Option_Chain_Calls$strike,
                               v  = db_Option_Chain_Calls$iv,
                               r  = db_Option_Chain_Calls$risk_free_rate,
                               tt = db_Option_Chain_Calls$days2Exp,
                               d  = db_Option_Chain_Calls$div_yield), complete = TRUE) %>%
      dplyr::select(k, s, Gamma) %>%
      dplyr::mutate(Date       = db_Option_Chain_Calls$expiry,
                    OI         = db_Option_Chain_Calls$open_interest %>% as.numeric(),
                    type       = "Calls",
                    Mul        = db_Option_Chain_Calls$Multiplier,
                    PriceRatio = db_Option_Chain_Calls$Price_Ratio,
                    GEX        = +1 * Gamma * Mul * OI * s^2 * 0.01) %>%
      dplyr::select(Date, k, s, GEX, PriceRatio, type)
    
    # GEX - Puts
    db_Option_Chain_Puts <- CBOE_General_Info %>%
      dplyr::filter(opt_type == "P") %>%
      dplyr::select(expiry, iv, open_interest, strike, Spot_Price, days2Exp, Time_Process, div_yield, risk_free_rate, Multiplier, Price_Ratio) %>%
      dplyr::mutate(type      = "Puts",
                    days2Exp  = days2Exp %>% as.numeric(),
                    days2Exp  = case_when(days2Exp == 0 ~ 1/365, TRUE ~ days2Exp/365),
                    Scenario1 = case_when(lubridate::week(expiry)  == lubridate::week(Time_Process) ~ "This Week",
                                          TRUE ~ "Not This Week"),
                    Scenario2 = case_when(lubridate::month(expiry)  == lubridate::month(Time_Process) ~ "This Month",
                                          TRUE ~ "Not This Month"),
                    Scenario3 = "All Dates")
    
    # GEX Calculations
    GEX_Puts <- greeks(bsput(s  = db_Option_Chain_Puts$Spot_Price,
                             k  = db_Option_Chain_Puts$strike,
                             v  = db_Option_Chain_Puts$iv,
                             r  = db_Option_Chain_Puts$risk_free_rate,
                             tt = db_Option_Chain_Puts$days2Exp,
                             d  = db_Option_Chain_Puts$div_yield), complete = TRUE) %>%
      dplyr::select(k, s, Gamma) %>%
      dplyr::mutate(Date       = db_Option_Chain_Puts$expiry,
                    OI         = db_Option_Chain_Puts$open_interest %>% as.numeric(),
                    type       = "Puts",
                    Mul        = db_Option_Chain_Puts$Multiplier,
                    PriceRatio = db_Option_Chain_Puts$Price_Ratio,
                    GEX        = -1 * Gamma * Mul * OI * s^2 * 0.01) %>%
      dplyr::select(Date, k, s, GEX, PriceRatio, type)
  
  # Combining all the DB of Options
  db_Option_Chain_Combined <- db_Option_Chain_Combined %>%
    rbind(db_Option_Chain_Calls) %>%
    rbind(db_Option_Chain_Puts)
  
  # Combining all the GEX DB
  acum_GEX <- acum_GEX %>%
    rbind(GEX_Calls) %>%
    rbind(GEX_Puts)
}

# Adjusting Strikes and Spot to the reference ticker
acum_GEX <- acum_GEX %>%
  dplyr::mutate(k = k * PriceRatio,
                s = s * PriceRatio)

# Selecting the Reference Price
Reference_Price <- db_prices_from_CBOE %>% 
  dplyr::filter(Ticker == Reference_Ticker) %>%
  dplyr::select(Reference_Price) %>% 
  pull(1)

# Netting GEX across all the strikes (Charts)
p <- acum_GEX %>%
  dplyr::select(k, GEX) %>%
  dplyr::group_by(k) %>%
  dplyr::filter(k > Reference_Price*0.80 & k < Reference_Price*1.20) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  purrr::set_names(c("Strike", "Gamma Exposure")) %>%
  ggplot(aes(x = Strike, y = `Gamma Exposure`)) +
  geom_bar(stat = "identity") +
  geom_vline(xintercept = Reference_Price, linetype = "dotted", color = "blue", size = 0.9) +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title    = str_glue("Total Gamma Exposure: {dollar_format()(sum(acum_GEX$GEX)/1000000000)} Billions per 1% move in the SP500"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {Chart_label})."), 
       caption  = "Data Source: CBOE / Own calculations.",
       x = "Strike Price",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal()

p

ggsave("GEX_vs_Strikes.png", plot = p, device = "png", path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in") 

# Getting the Put Wall and the Call Wall
acum_GEX %>%
  dplyr::select(k, GEX) %>%
  dplyr::group_by(k) %>%
  dplyr::filter(k > Reference_Price*0.80 & k < Reference_Price*1.20) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>% 
  slice_min(GEX_NET, with_ties = FALSE) -> Put_Wall

acum_GEX %>%
  dplyr::select(k, GEX) %>%
  dplyr::group_by(k) %>%
  dplyr::filter(k > Reference_Price*0.80 & k < Reference_Price*1.20) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>% 
  slice_max(GEX_NET, with_ties = FALSE) -> Call_Wall

# GEX (Next Two Months)
p <- acum_GEX %>%
  dplyr::select(Date, GEX) %>%
  dplyr::group_by(Date) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  dplyr::mutate(Month = lubridate::month(Date),
                Month_Filter = ifelse(Date <= Sys.Date() + 60, "Yes", "No")) %>%
  dplyr::filter(Month_Filter == "Yes") %>%
  dplyr::select(Date, GEX_NET) %>%
  purrr::set_names(c("Date", "Gamma Exposure")) %>%
  ggplot(aes(x = Date, y = `Gamma Exposure`)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title    = str_glue("Total Gamma Exposure by Expiration Date - Next Two Months"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {Chart_label})."), 
       caption  = "Data Source: CBOE / Own calculations.",
       x = "Expiration Date",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal()

p

ggsave("GEX_vs_Next_Two_Months.png", plot = p, device = "png", path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in") 

# GEX across Strikes and option type
p <- acum_GEX %>%
  dplyr::select(k, type, GEX) %>%
  dplyr::filter(k > Reference_Price*0.80 & k < Reference_Price*1.20) %>%
  dplyr::group_by(k, type) %>%
  dplyr::summarise(GEX_NET = sum(GEX)/1000000000) %>%
  purrr::set_names(c("Strike", "Type", "Gamma Exposure")) %>%
  ggplot(aes(x = Strike, y = `Gamma Exposure`, fill = Type)) +
  geom_vline(xintercept = Reference_Price, linetype = "dotted", color = "blue", size = 0.9) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c(Calls = "green", Puts = "red")) +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(title    = str_glue("Total Gamma Exposure: {dollar_format()(sum(acum_GEX$GEX)/1000000000)} Billions per 1% move in the SP500"),
       subtitle = str_glue("Assuming dealers are long calls and short puts (considering: {Chart_label})."), 
       caption  = "Data Source: CBOE / Own calculations.",
       x = "Strike Price",
       y = "Spot Gamma Exposure (Billions)") +
  theme_minimal() +
  theme(legend.title = element_blank())

p

ggsave("GEX_vs_Option_Types.png", plot = p, device = "png", path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in") 

# Calculating the Gamma Exposure Profile
db_GEX_Profile <- NULL 

for(blocks in 13:15){ # blocks <- 13
  
  # Filtering
  if(blocks == 13){
    db_Option_Chain_New <- db_Option_Chain_Combined[, 1:blocks] %>% dplyr::filter(Scenario1 == "Not This Week")
    block_Label         <- "W/out this Week"
  }else if(blocks == 14){
    db_Option_Chain_New <- db_Option_Chain_Combined[, 1:blocks] %>% dplyr::filter(Scenario2 == "Not This Month")
    block_Label         <- "W/out this Month" 
  }else{
    db_Option_Chain_New <- db_Option_Chain_Combined
    block_Label         <- "All Expirations"
  }
  
  # Setting the Delta in price
  Spot_Steps <- seq(-20, 20, 0.1)
  
  for(new_step in Spot_Steps){ # new_step <- 0
    
    # GEX for the Calls
    # CALLS
    db_Options_Type_Subset <- db_Option_Chain_New %>% dplyr::filter(type == "Calls")

    GEX_Calls <- greeks(bscall(s  = db_Options_Type_Subset$Spot_Price*(1 + new_step/100),
                               k  = db_Options_Type_Subset$strike,
                               v  = db_Options_Type_Subset$iv,
                               r  = db_Options_Type_Subset$risk_free_rate,
                               tt = db_Options_Type_Subset$days2Exp,
                               d  = db_Options_Type_Subset$div_yield), complete = TRUE) %>%
      dplyr::select(k, s, Gamma) %>%
      dplyr::mutate(Date       = db_Options_Type_Subset$expiry,
                    OI         = db_Options_Type_Subset$open_interest %>% as.numeric(),
                    type       = "Calls",
                    Mul        = db_Options_Type_Subset$Multiplier,
                    PriceRatio = db_Options_Type_Subset$Price_Ratio,
                    GEX        = +1 * Gamma * Mul * OI * s^2 * 0.01) %>%
      dplyr::select(Date, k, s, GEX, PriceRatio, type)
    
    # PUTS
    db_Options_Type_Subset <- db_Option_Chain_New %>% dplyr::filter(type == "Puts")
    
    GEX_Puts <- greeks(bsput(s  = db_Options_Type_Subset$Spot_Price*(1 + new_step/100),
                             k  = db_Options_Type_Subset$strike,
                             v  = db_Options_Type_Subset$iv,
                             r  = db_Options_Type_Subset$risk_free_rate,
                             tt = db_Options_Type_Subset$days2Exp,
                             d  = db_Options_Type_Subset$div_yield), complete = TRUE) %>%
      dplyr::select(k, s, Gamma) %>%
      dplyr::mutate(Date       = db_Options_Type_Subset$expiry,
                    OI         = db_Options_Type_Subset$open_interest %>% as.numeric(),
                    type       = "Puts",
                    Mul        = db_Options_Type_Subset$Multiplier,
                    PriceRatio = db_Options_Type_Subset$Price_Ratio,
                    GEX        = -1 * Gamma * Mul * OI * s^2 * 0.01) %>%
      dplyr::select(Date, k, s, GEX, PriceRatio, type)
    
    # Combining all the GEX DB
    db_GEX_Spot <- GEX_Puts %>% rbind(GEX_Calls)
    
    # Saving the calculations in a provisional Dataframe
    db_GEX_Profile_prov <- data.frame(Spot_Change = new_step,
                                      GEX         = sum(db_GEX_Spot$GEX %>% replace(is.na(.), 0)),
                                      Expiration  = block_Label)
    
    # Accumulating 
    db_GEX_Profile <- db_GEX_Profile %>% rbind(db_GEX_Profile_prov)
  }
}

Gamma_Flip <- db_GEX_Profile %>%
  dplyr::filter(Expiration == "All Expirations") %>%
  dplyr::mutate(Flip = ifelse(dplyr::lead(GEX > 0) & GEX < 0, "Yes", "No")) %>%
  dplyr::filter(Flip == "Yes") %>%
  dplyr::select(Spot_Change) %>%
  pull(1) %>% first()

# GEX Profile applying locally weighted scatterplot smoothing (removing the noice of the calculations)
p <- db_GEX_Profile %>%
  dplyr::filter(Expiration == "All Expirations") %>%
  dplyr::mutate(Spot_Change = lowess(Spot_Change, GEX, f = 1/10) %>% pluck(1),
                GEX         = (lowess(Spot_Change, GEX, f = 1/10) %>% pluck(2))/1000000000) %>%
  ggplot(aes(Spot_Change/100, GEX)) + 
  geom_rect(inherit.aes = TRUE,
            aes(xmin = -Inf, xmax = Gamma_Flip/100, ymin = -Inf, ymax = +Inf), 
            fill = 'red', alpha = 0.005) +
  geom_rect(inherit.aes = TRUE,
            aes(xmin = Gamma_Flip/100, xmax = +Inf, ymin = -Inf, ymax = +Inf), 
            fill = 'green', alpha = 0.005) +
  geom_line(size = 1.3, colour = "black") +
  geom_vline(xintercept = c(0, Gamma_Flip/100), linetype = c("twodash", "dotted"), color = c("steelblue", "red"), size = 0.9) +
  geom_hline(yintercept = c(sum(acum_GEX$GEX)/1000000000, 0), linetype = c("twodash", "dotted"), color = c("steelblue", "red"), size = 0.9) +
  labs(title    = str_glue("Gamma Exposure Profile of the SP500 - All expirations (Current GEX {dollar_format()(sum(acum_GEX$GEX)/1000000000)} Billions)."),
       subtitle = str_glue("Gamma Flip at {round(Gamma_Flip, digits = 2)}% of current price (meaning at: {round(Reference_Price*(1+Gamma_Flip/100), digits = 2)}). Assuming dealers are long calls and short puts (considering: {Chart_label})."),
       caption  = "Data Source: CBOE / Own calculations.",
       x = "Change in SPX Price",
       y = "Spot Gamma Exposure (Billions)") +
  scale_y_continuous(labels = scales::dollar_format(),
                     breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = scales::pretty_breaks(n = 10),
                     sec.axis = sec_axis(trans = ~ . * Reference_Price + Reference_Price, name = "SPX Price", breaks = scales::pretty_breaks(n = 10))) +
  theme(legend.title = element_blank()) + 
  geom_vline(xintercept = (Put_Wall %>% dplyr::select(k) %>% pull(1))/Reference_Price - 1, linetype = "dotted", color = "red", size = 2.5) +
  geom_vline(xintercept = (Call_Wall %>% dplyr::select(k) %>% pull(1))/Reference_Price - 1, linetype = "dotted", color = "blue", size = 2.5)

p

ggsave("GEX_Profile_All_Expirations.png", plot = p, device = "png", path = "Plots - GEX CBOE/", width = 15, height = 7, units = "in")


# Analyzing the Impact of Different Expiration.
p <- db_GEX_Profile %>%
  ggplot(aes(Spot_Change/100, GEX/1000000000, group = Expiration, colour = Expiration)) + 
  theme_minimal() +
  geom_line(size = 1.3) +
  scale_color_viridis(discrete = TRUE) +
  geom_vline(xintercept = c(0, Gamma_Flip/100), linetype = c("dotted", "dotted"), color = c("steelblue", "red"), size = 0.9) +
  geom_hline(yintercept = c(sum(acum_GEX$GEX)/1000000000, 0), linetype = c("dotted", "dotted"), color = c("steelblue", "red"), size = 0.9) +
  labs(title    = str_glue("Gamma Exposure Profile of the SP500. Analyzing different Scenarios (Current GEX {dollar_format()(sum(acum_GEX$GEX)/1000000000)} Billions)."),
       subtitle = str_glue("Gamma Flip at {round(Gamma_Flip, digits = 2)}% of current price (meaning at: {round(Reference_Price*(1+Gamma_Flip/100), digits = 2)}). Assuming dealers are long calls and short puts (considering: {Chart_label})."),
       caption  = "Data Source: CBOE / Own calculations.",
       x = "Change in SPX Price",
       y = "Spot Gamma Exposure (Billions)") +
  scale_y_continuous(labels = scales::dollar_format(),
                     breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1),
                     breaks = scales::pretty_breaks(n = 10),
                     sec.axis = sec_axis(trans = ~ . * Reference_Price + Reference_Price, name = "SPX Price", breaks = scales::pretty_breaks(n = 10))) +
  theme(legend.title = element_blank())  

p

ggsave("GEX_Profile_Scenarios.png", plot = p, device = "png", path = "Plots - GEX CBOE/", width = 15, height = 7, units = "in") 

# Extracting the VIX Structure from the Option Chain
MMS_First_Criteria  <- 0.95    # Moneyness criteria for the Implied Volatility Structure
MMS_Second_Criteria <- 1.05    # Moneyness criteria for the Implied Volatility Structure

ATM_Price         <- Reference_Price
MoneynessFC_Price <- ATM_Price*MMS_First_Criteria
MoneynessSC_Price <- ATM_Price*MMS_Second_Criteria

p <- db_Option_Chain_Combined %>% 
  dplyr::select(expiry, type, iv, strike, Price_Ratio) %>%
  dplyr::mutate(strike = (strike %>% as.numeric()) * Price_Ratio) %>%
  dplyr::filter(type == "Puts" & expiry >= Sys.Date()) %>%
  dplyr::mutate(final_date = expiry %>% as.Date()) %>%
  dplyr::mutate(VST = ifelse(dplyr::lead(strike, n = 1) > ATM_Price & dplyr::lag(strike, n = 1) < ATM_Price, "ATM", 
                             ifelse(dplyr::lead(strike, n = 1) > MoneynessFC_Price & dplyr::lag(strike, n = 1) < MoneynessFC_Price, str_glue("MM{MMS_First_Criteria*100}"), 
                                    ifelse(dplyr::lead(strike, n = 1) > MoneynessSC_Price & dplyr::lag(strike, n = 1) < MoneynessSC_Price, str_glue("MM{MMS_Second_Criteria*100}"), "")))) %>% 
  dplyr::filter(VST != "") %>%
  dplyr::select(final_date, iv, VST) %>%
  dplyr::group_by(final_date, VST) %>%
  dplyr::summarise(Mean_IV = mean(iv %>% as.numeric()), .groups = "drop") %>%
  dplyr::mutate(VST = case_when(VST == str_glue("MM{MMS_First_Criteria*100}") ~ str_glue("Moneyness {MMS_First_Criteria*100}%"),
                                VST == str_glue("MM{MMS_Second_Criteria*100}") ~ str_glue("Moneyness {MMS_Second_Criteria*100}%"),
                                TRUE ~ VST)) %>%
  dplyr::group_by(VST) %>%
  dplyr::mutate(Mean_IV = (lowess(final_date, Mean_IV, f = 1/2) %>% pluck(2))) %>%
  ggplot(aes(x = final_date, y = Mean_IV, colour = VST)) +
  geom_line(linewidth = 0.9) +
  labs(title    = "Implied Volatility Structure",
       subtitle = "Data extracted from the Option Chain (Combining SPX, XSP and SPY)",
       caption  = "Data Source: CBOE / Own calculations.",
       x        = "",
       y        = "Implied Volatility") +
  scale_y_continuous(labels = scales::percent) +
  theme(legend.title = element_blank(),
        legend.position = "bottom")

p

ggsave("vix_structure.png", plot = p, path = "Plots - GEX CBOE/", width = 10, height = 7, units = "in") 

# Stoping the Timer
tictoc::toc()
